# job_id: large_scale
job_id: AR-segmentation_lora_r32_a64_d0.1
data:
  # Use this to point at the paths of HelioFM data indices
  train_data_path: ./assets/sdo_validate.csv
  valid_data_path: ./assets/sdo_test.csv
  channels: ['aia94', 'aia131', 'aia171', 'aia193', 'aia211', 'aia304', 'aia335', 'aia1600', 'hmi_m', 'hmi_bx', 'hmi_by', 'hmi_bz', 'hmi_v']
  time_delta_input_minutes: [0]
  time_delta_target_minutes: +60
  # n_input_timestamps: 1 #Optional integer to randomly sample time_delta_input_minutes
  batch_size: 1
  num_data_workers: 8
  prefetch_factor: 2
  scalers_path: ../../data/Surya-1.0/scalers.yaml
  #### Put your donwnstream (DS) specific parameters below this line
  ar_index_train: ["./assets/ar_2011.csv","./assets/ar_2012.csv","./assets/ar_2013.csv"]
  ar_index_valid: ["./assets/ar_2014.csv"]
  ar_index_test: ["./assets/ar_2014.csv"]
model:
  model_type: spectformer_lora # Options: unet, spectformer, persistence, flow
  # Spectformer options
  img_size: 4096
  patch_size: 16
  in_channels: 13
  time_embedding:
    type: linear           # Options: linear, perceiver
    n_queries: null        # Integer for perceiver; otherwise null
    time_dim: 1            # Integer
  embed_dim: 1280
  depth: 10
  spectral_blocks: 2
  num_heads: 16
  mlp_ratio: 4.0
  rpe: false
  drop_rate: 0.0
  window_size: 2
  dp_rank: 4
  learned_flow: false
  epochs_to_learn_flow: 0 # Start by training flow model only before freezing
  init_weights: false
  checkpoint_layers: []
  ensemble: null # Set to integer or null
  finetune: True
  # Finetuning config fields
  ft_unembedding_type: "linear" # "linear" or "perceiver"
  ft_out_chans: 1
  use_lora: true
  lora_config:
    r: 32  # LoRA rank
    lora_alpha: 64  # LoRA alpha parameter
    target_modules: ['q_proj', 'v_proj', 'k_proj', 'out_proj', 'fc1', 'fc2']  # Target modules for LoRA
    lora_dropout: 0.1
    bias: 'none'
    # task_type: 'SEQ_CLS'

  # metrics for AR segmentation
  select: "bce"
  dice:
    smooth: 1e-5
  iou:
    eps: 1e-6
  bce:
    pos_weight: 1

optimizer:
  warm_up_steps: 0 #2000
  max_epochs: 15
  learning_rate: 0.001
  min_lr: 0.000001
use_latitude_in_learned_flow: false
loss_weights: [] # [] or list of weights per channel
rollout_steps: 0
num_mask_aia_channels: 0
drop_hmi_probablity: 0.0
validate_after_epoch: 1
wandb_log_train_after: 5 # This should be less than iters_per_epoch_train
wandb_project: "helio-fm" # Typical choices: "helio-fm", "spectformer_with_metrics"
visualization_samples: 3
save_wt_after_iter: 100000
path_experiment: checkpoints
iters_per_epoch_train: 2000
iters_per_epoch_valid: 200
iters_grad_accum: 1
dtype: bfloat16
parallelism: "ddp" # Valid options: "ddp" and "fsdp"

# Finetuning config fields
pretrained_path: ../../data/Surya-1.0/surya.366m.v1.pt
freeze_backbone: False
