job_id: solar_flare_forcasting
data:
  sdo_data_root_path: ./assets/infer_data
  valid_data_path: ./assets/infer_data/infer_index_surya_1_0.csv
  flare_data_path: ./assets/surya-bench-flare-forecasting/validation.csv
  channels: ['aia94', 'aia131', 'aia171', 'aia193', 'aia211', 'aia304', 'aia335', 'aia1600', 'hmi_m', 'hmi_bx', 'hmi_by', 'hmi_bz', 'hmi_v']
  time_delta_input_minutes: [-60,0]
  time_delta_target_minutes: +60
  n_input_timestamps: 2 # must be equal to time_delta_input_minutes
  batch_size: 1
  num_data_workers: 4
  prefetch_factor: 2
  pooling: 1
  random_vert_flip: false
  scalers_path: ../../data/Surya-1.0/scalers.yaml

model:
  model_type: spectformer # New model type for PEFT LoRA finetuning
  # Spectformer options
  img_size: 4096
  patch_size: 16
  in_channels: 13
  time_embedding:
    type: linear      # Options: linear, fourier, perceiver
    n_queries: null   # Integer for perceiver; otherwise null
    time_dim: 2       # Integer for linear and fourier; otherwise null
  unet_embed_dim: null
  unet_blocks: null
  unet_concat_activations: false # Whether to concatenate activations (UNet) or not (Autoencoder/bottleneck) in the decoder
  embed_dim: 1280
  depth: 10
  spectral_blocks: 2
  num_heads: 16
  mlp_ratio: 4.0
  rpe: false
  drop_rate: 0.0
  window_size: 2
  dp_rank: 4
  learned_flow: false
  epochs_to_learn_flow: 0 # Start by training flow model only before freezing
  init_weights: false
  checkpoint_layers: [0,1,2,3,4,5,6,7,8,9]
  ensemble: null
  finetune: true
  nglo: 1
  global_average_pooling: False
  global_max_pooling: False
  attention_pooling: False
  transformer_pooling: False
  global_class_token: True
  penultimate_linear_layer: True
  freeze_backbone: false  # Set to False for full model finetuning with LoRA
  dropout: 0.2
  # PEFT LoRA configuration
  use_lora: true
  lora_config:
    r: 8  # LoRA rank
    lora_alpha: 8  # LoRA alpha parameter
    target_modules: ['q_proj', 'v_proj', 'k_proj', 'out_proj', 'fc1', 'fc2']  # Target modules for LoRA
    lora_dropout: 0.1
    bias: 'none'
    # task_type: 'SEQ_CLS'

classifier_metrics:
  task: "binary"  # ["binary", "multiclass", "multilabel"]
  num_classes: 2
  average: 'macro'  # ["micro", "macro", "weighted", "none"]
  train_metrics_config:
    metrics_to_report: ["accuracy", "precision", "recall", "f1"]
  validation_metrics_config:
    metrics_to_report: ["accuracy", "precision", "recall", "f1"]

optimizer:
  warm_up_steps: 0 #2000
  max_epochs: 20
  learning_rate: 0.0001  # Can use higher learning rate with LoRA
  min_lr: 0.00001

use_latitude_in_learned_flow: false
pretrained_path: ../../data/Surya-1.0/surya.366m.v1.pt
# from_checkpoint: <PATH TO BEST CHECKPOINT linembed-input1_0.1>
loss_weights: [] # [] or list of weights per channel
rollout_steps: 0
num_mask_aia_channels: 0
drop_hmi_probability: 0.0
validate_after_epoch: 1
wandb_log_train_after: 100 # This should be less than iters_per_epoch_train
wandb_project: "helio-fm" # Typical choices: "helio-fm", "spectformer_with_metrics"
visualization_samples: 3
save_wt_after_iter: 1000
path_experiment: checkpoints
iters_per_epoch_train: 2000
iters_per_epoch_valid: 200
iters_grad_accum: 1
dtype: float32
parallelism: "ddp" # Valid options: "ddp" and "fsdp" 
